title: Lightyear Frontier - Crop Calculator
email: howzit@hinoshi.dev
description: >- # this means to ignore newlines until "baseurl:"
  A simple application that generates the best rotation for your crops in Lightyear Frontier.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cropcalc.lyf.hinoshi.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: marssza

# Build settings
plugins:
  - jekyll-feed
